export const adFormFields = {
  title: {
    label: "Título",
    type: "text",
    name: "title",
    minLength: 3,
    maxLength: 100,
    required: true,
    placeholder: "Título do serviço, negócio, evento ou produto",
  },
  short: {
    label: "Descrição resumida",
    type: "text",
    name: "short",
    maxLength: 255,
    placeholder: "Descrição resumida",
  },
  description: {
    label: "Descrição detalhada",
    type: "textarea",
    name: "description",
    maxLength: 2000,
    rows: 8,
    placeholder: "Coloque aqui a descrição detalhada de seu negócio...",
  },
  tags: {
    label: "Tags, palavras-chave",
    type: "text",
    name: "tags",
    maxLength: 255,
    placeholder: "Informe as palavras-chave (tags)...",
  },
  zipcode: {
    label: "CEP",
    type: "text",
    name: "zipcode",
    maxLength: 9,
    minLength: 8,
    required: false,
    placeholder: "CEP",
    pattern: /^\d{5}-?\d{3}$/,
    patternError: "Informe o CEP no formato xxxxxxxx ou xxxxx-xxx",
  },
  city: {
    label: "Cidade",
    type: "text",
    name: "city",
    maxLength: 30,
    placeholder: "Cidade",
    readOnly: true,
    tabIndex: -1,
  },
  state: {
    label: "Estado",
    type: "text",
    name: "state",
    maxLength: 2,
    placeholder: "Estado",
    readOnly: true,
    tabIndex: -1,
  },
  address1: {
    label: "Endereço",
    type: "text",
    name: "address1",
    maxLength: 100,
    placeholder: "exemplo: Av. Mandaqui",
    readOnly: true,
    tabIndex: -1,
  },
  streetNumber: {
    label: "Número",
    type: "text",
    name: "streetNumber",
    maxLength: 20,
    placeholder: "197",
  },
  address2: {
    label: "Complemento",
    type: "text",
    name: "address2",
    maxLength: 100,
    placeholder: "exemplo: sala 32, Limão",
  },
  radius: {
    label: "Raio de Atendimento",
    type: "select",
    name: "radius",
    options: [
      { value: "0", label: "----" },
      { value: "1", label: "até 1 km" },
      { value: "2", label: "até 2 km" },
      { value: "3", label: "até 3 km" },
      { value: "4", label: "até 4 km" },
      { value: "5", label: "até 5 km" },
      { value: "10", label: "até 10 km" },
      { value: "15", label: "até 15 km" },
      { value: "20", label: "até 20 km" },
      { value: "25", label: "até 25 km" },
      { value: "30", label: "até 30 km" },
      { value: "35", label: "até 35 km" },
      { value: "40", label: "até 40 km" },
      { value: "45", label: "até 45 km" },
      { value: "50", label: "até 50 km" },
      { value: "60", label: "até 60 km" },
      { value: "70", label: "até 70 km" },
      { value: "80", label: "até 80 km" },
      { value: "90", label: "até 90 km" },
      { value: "100", label: "até 100 km" },
      { value: "150", label: "até 150 km" },
      { value: "200", label: "até 200 km" },
    ],
  },
  phone1: {
    label: "Telefone 1",
    type: "text",
    name: "phone1",
    maxLength: 20,
    placeholder: "(xx)xxxx-xxxx",
  },
  phone2: {
    label: "Telefone 2",
    type: "text",
    name: "phone2",
    maxLength: 20,
    placeholder: "(xx)xxxx-xxxx",
  },
  whatsapp: {
    label: "WhatsApp",
    type: "text",
    name: "whatsapp",
    maxLength: 20,
    placeholder: "(xx)xxxx-xxxx",
  },
  email: {
    label: "Email",
    type: "email",
    name: "email",
    maxLength: 100,
    placeholder: "Email",
  },
  website: {
    label: "Website",
    type: "url",
    name: "website",
    maxLength: 100,
    placeholder: "exemplo: https://www.ondetem.org",
  },
  startdate: {
    label: "Data Inicial",
    type: "date",
    name: "startdate",
  },
  finishdate: {
    label: "Data Final",
    type: "date",
    name: "finishdate",
  },
  timetext: {
    label: "Horários",
    type: "textarea",
    name: "timetext",
    maxLength: 1000,
    rows: 6,
    placeholder: "Horários",
  },
};
