export const userFormFields = {
  name: {
    label: "Nome Completo",
    type: "text",
    value: "",
    name: "fullName",
    maxLength: 100,
    required: true,
    placeholder: "Nome Completo",
  },
  firstName: {
    label: "Primeiro Nome",
    type: "text",
    value: "",
    name: "firstName",
    maxLength: 20,
    required: true,
    placeholder: "Primeiro nome",
  },
  nickname: {
    label: "Apelido",
    type: "text",
    value: "",
    name: "nickname",
    maxLength: 20,
    required: true,
    placeholder: "Apelido",
  },
  email: {
    label: "Email",
    type: "email",
    value: "",
    name: "email",
    required: true,
    placeholder: "Email",
  },
  password: {
    label: "Senha",
    type: "password",
    value: "",
    name: "password",
    required: true,
    placeholder: "Senha",
  },
  password2: {
    label: "Confirme a senha",
    type: "password",
    value: "",
    name: "password2",
    required: true,
    placeholder: "Confirme a senha",
  },
};
